### ISSUE TITLE
PowerShell support

### ISSUE THREAD

**Issue by heikki** [dab00/nvmx#1]
Do you have any plans on supporting powershell?

![screen shot 2015-02-16 at 09 17 15](https://cloud.githubusercontent.com/assets/82735/6212551/ff9ff1b6-b5bc-11e4-87ba-a19237a057a7.png)

**Comment by dab00** [comment]
Currently no, is it necessary for you?

**Comment by heikki** [comment]
It's mainly for convenience because Github for Windows uses powershell.
https://help.github.com/articles/do-i-need-to-install-anything-extra/

**Comment by dab00** [comment]
ok i'll try, can't promise it'll be soon

**Comment by dab00** [comment]
Now I can promise I'll do it at saturday. Or you can just edit nvmx.bat file: 
- remove this: set "path=%nvmx%"
- insert this: powershell.exe -NoExit -Command "Set-Item Env:Path -Value '%nvmx%'"
Hope it help

**Comment by heikki** [comment]
Oh, it was that simple. Thanks!
