### ISSUE TITLE
Global bins not in path

### ISSUE THREAD

**Issue by heikki** [dab00/nvmx#2]
![screen shot 2015-02-19 at 16 17 46](https://cloud.githubusercontent.com/assets/82735/6275155/4e39e24e-b853-11e4-9c3c-123a38063c9e.png)

Same with command prompt and powershell.  Let me know if this works for you and I'll debug further.

**Comment by dab00** [comment]
Thanks! I'll try fix it at weekend, currently very busy, sorry

**Comment by dab00** [comment]
I've tried to fix it, so you may check out

**Comment by heikki** [comment]
It's working now, thanks. :+1: 

ps. Global modules seem to be shared between node versions. Is that intentional?

**Comment by dab00** [comment]
I think yes, it's **global** :)

**Comment by heikki** [comment]
Ok, for example [nvm](https://github.com/creationix/nvm) handles them separately: 

```
∴ ~ npm list -g
/Users/heikki/.nvm/versions/node/v0.12.0/lib
├── gulp@3.8.11
└── npm@2.5.1
```

**Comment by dab00** [comment]
I made this tool in the first place for myself and I think global modules should be shared between all versions. I don't care of any nvm, but I'm ready to consider your arguments.

**Comment by heikki** [comment]
No problem :smile: 
I was just wondering if there's some good reason why they are separate elsewhere.

**Comment by dab00** [comment]
If there's some good reason I'd like to know this reason :), I can't see any

**Comment by heikki** [comment]
Well, I keep my eyes open. Thanks again!
